# Generated by Django 5.2.6 on 2025-09-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='excelplanilha',
            table='planilhas',
        ),
    ]
